import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import NavbarMenu from "@/components/Navbar";
import Footer from "@/components/Footer";

const kanit = Kanit({
  subsets: ["thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <NavbarMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
